Saving last configuration file to .certora_internal/24_05_14_18_00_33_109/run.conf
There is no TAC file. Going to script EVMVerifier/certoraBuild.py to main_with_args()
Creating dir /home/shan/my_project/Dao-tests/SprialDao/.certora_internal/24_05_14_18_00_33_109/.certora_config
In /home/shan/my_project/Dao-tests/SprialDao/BurnMint.spec, found the imports: [('./IERC20.spec', '5:2'), ('/IERC2612.spec ', '6:2')]
build failed
Failure traceback: 
CertoraUserInputError: In /home/shan/my_project/Dao-tests/SprialDao/BurnMint.spec, the following import declarations do not import existing .spec files:
6:2:"/IERC2612.spec "

Encountered an error running Certora Prover:
In /home/shan/my_project/Dao-tests/SprialDao/BurnMint.spec, the following import declarations do not import existing .spec files:
6:2:"/IERC2612.spec "

